import Layout from "@/components/global/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/profile-dev.jpg";
import Link from "next/link";
import AnimatedText from "@/components/Global/AnimatedText";
import { LinkArrow } from "@/components/global/Icons";

import ContactShortcut from "@/components/home/ContactShortcut";
import ColorsCircle from "@/components/Global/ColorsCircle";
import Differeciales from "@/components/Home/Differeciales";
import Quote from "@/components/Home/Quote";
import CallToAction from "@/components/Global/CallToAction";

export default function Home() {
  return (
    <>
      <Head>
        <title>Alan Alves</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark dark:text-light w-full min-h-screen">
        <Layout className="pt-24">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Olá, me chamo Alan Alves, sou desenvolvedor web, com ênfase na experiência do usuário."
                className="!text-5xl text-left lg:!text-center md:!text-4xl sm:!text-3xl xs:!text-2xl"
              />
              <p className="my-4 text-base font-medium">
                Como desenvolvedor web qualificado, estou comprometido em
                transformar conceitos e aspirações em aplicações web inovadoras
                e de fácil utilização. Conto com um amplo conjunto de
                habilidades, com proficiência em HTML, CSS e JavaScript.
                Atualmente, atuo como freelancer, concentrando-me principalmente
                no desenvolvimento web utilizando React.js e Next.js.
              </p>
              <div className="flex items-center self-center mt-2">
                <Link
                  href="/Curriculo_Alan_Alves.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-5
                rounded-lg text-base font-semibold text-nowrap hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                "
                  download={true}
                >
                  Baixar CV <LinkArrow className={"w-4 ml-1"} />
                </Link>
                <Link
                  href="mailto:alan.blmv@gmail.com"
                  target="_blank"
                  className="ml-4 text-lg font-medium capitalize text-dark dark:text-light underline"
                  // border border-solid border-transparent analisando um método melhor para o hover
                  // hover:border-dark hover:text-underline
                >
                  Contato
                </Link>
              </div>
            </div>

            <div className="w-1/2 mr-2 md:w-full md:mt-24 md:mr-0">
              <Quote />
              {/* <Image
                src={profilePic}
                alt="Alan Alves"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="
                (max-width: 768px) 100vw,
                (max-width: 1200px) 50vw, 50vw"
              /> */}
            </div>
          </div>

          <div className="flex items-center justify-between w-full mt-24">
            <AnimatedText
              text="Transformando sonhos em realidade com código, design e amor."
              className="!text-5xl text-pretty xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-4xl sm:!text-3xl xs:text-2xl"
            />
          </div>

          <Differeciales />

          <CallToAction
            title="Gostou do que viu?"
            subtitle="Vamos criar algo incrível juntos."
            buttonText="Entre em Contato"
            link="/contact"
          />
        </Layout>

        <ContactShortcut />
        <ColorsCircle />
      </main>
    </>
  );
}
