import Layout from "@/components/Global/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/profile-dev.jpg";
import Link from "next/link";
import AnimatedText from "@/components/Global/AnimatedText";
import {
  BankNotesIcon,
  Flexibility,
  LinkArrow,
  PersonalizedService,
  RocketIcon,
  SupportIcon,
  UserPersonFocus,
  WhatsAppIconContact,
} from "@/components/Global/Icons";

import ContactShortcut from "@/components/Home/ContactShortcut";
import ColorsCircle from "@/components/Global/ColorsCircle";
import Differeciales from "@/components/Home/Differeciales";

export default function Home() {
  return (
    <>
      <Head>
        <title>Alan Alves</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark dark:text-light w-full min-h-screen">
        <Layout className="pt-24">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Olá, me chamo Alan Alves, sou desenvolvedor web, com ênfase na experiência do usuário."
                className="!text-5xl text-left"
              />
              <p className="my-4 text-base font-medium">
                Como desenvolvedor web qualificado, estou comprometido em
                transformar conceitos e aspirações em aplicações web inovadoras
                e de fácil utilização. Conto com um amplo conjunto de
                habilidades, com proficiência em HTML, CSS e JavaScript.
                Atualmente, atuo como freelancer, concentrando-me principalmente
                no desenvolvimento web utilizando React.js.
              </p>
              <div className="flex items-center self-center mt-2">
                <Link
                  href="/dummy.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-5
                rounded-lg text-base font-semibold text-nowrap hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                "
                  download={true}
                >
                  Baixar CV <LinkArrow className={"w-4 ml-1"} />
                </Link>
                <Link
                  href="mailto:alan.blmv@gmail.com"
                  target="_blank"
                  className="ml-4 text-lg font-medium capitalize text-dark dark:text-light underline"
                  // border border-solid border-transparent analisando um método melhor neste hover
                  // hover:border-dark hover:text-underline
                >
                  Contato
                </Link>
              </div>
            </div>

            <div className="w-1/2 mr-2">
              <Image
                src={profilePic}
                alt="Alan Alves"
                className="w-full h-auto"
                priority
                sizes="
                (max-width: 768px) 100vw,
                (max-width: 1200px) 50vw, 50vw"
              />
            </div>
          </div>

          <div className="flex items-center justify-between w-full mt-24">
            <AnimatedText
              text="Transformando sonhos em realidade com código, design e amor."
              className="!text-5xl text-pretty"
            />
          </div>

          <Differeciales />

          <div className="w-full relative py-10 px-20 mt-24 flex items-center justify-between rounded-2xl border border-solid border-dark bg-light dark:bg-dark dark:border-light ">
            <div
              className="absolute top-1 -right-3 -z-10 w-[101%] h-[103%] rounded-[2rem] bg-dark 
                rounded-br-3xl"
            />
            <div
              className="absolute top-3 -right-5 -z-20 w-[102%] h-[103%] rounded-[2rem] bg-gray-700 
                rounded-br-3xl"
            />
            <div
              className="absolute top-5 -right-7 -z-30 w-[102%] h-[103%] rounded-[2rem] bg-gray-600 
                rounded-br-3xl"
            />
            <div
              className="absolute top-7 -right-9 -z-40 w-[102%] h-[103%] rounded-[2rem] bg-gray-300 
                rounded-br-3xl"
            />

            <div className="px-20">
              <h3 className="text-dark dark:text-light text-4xl font-medium">
                Você se Interessou?
              </h3>
              <p className=" text-dark dark:text-light text-lg">
                Tem algum pojeto a ser construido?
              </p>
            </div>
            <Link
              href="/contact"
              className="flex items-center bg-dark text-light p-2.5 px-5
                rounded-lg text-base font-semibold text-nowrap hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
            >
              Vamos Trabalhar Juntos!
            </Link>
          </div>
        </Layout>

        <ContactShortcut />
        <ColorsCircle />
      </main>
    </>
  );
}
