import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/profile-dev.jpg";
import Link from "next/link";
import AnimetedText from "@/components/AnimetedText";
import { LinkArrow } from "@/components/Icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2 mr-2">
              <Image
                src={profilePic}
                alt="Alan Alves"
                className="w-full h-auto"
              />
            </div>

            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimetedText
                text="Transformando sonhos em realidade com código, design e amor."
                className="!text-6xl text-left"
              />
              <p className="my-4 text-base font-medium">
                Como desenvolvedor front-end qualificado, empenho-me em
                transformar ideias e aspirações em aplicações web inovadoras e
                simplificadas. Possuo um conjunto de ferramentas diversificado,
                com ênfase em React.js, centrado principalmente no
                desenvolvimento web.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/dummy.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                "
                  download={true}
                >
                  Resumo <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:alan.blmv@gmail.com"
                  target="_blank"
                  className="ml-4 text-lg font-medium capitalize text-dark underline"
                  // border border-solid border-transparent analisando um método melhor neste hover
                  // hover:border-dark hover:text-underline
                >
                  Contato
                </Link>
              </div>
            </div>
          </div>
        </Layout>

      </main>
    </>
  );
}
